name: Build and push docker images
on:
  workflow_run:
    workflows: ["Packed and release Yao-Litemall"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tags:
        description: "Comment"
  push:
    branches: [main]
env:
  IMAGE_ORG: wwsheng009
  IMAGE_NAME: ${{ github.event.repository.name }}
  REPO_DOCKERFILES: ${{ github.repository_owner }}/dockerfiles
  VERSION: 1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Source
        uses: actions/checkout@v2

      - name: Get Version
        run: |
          VERSION=1.0.0
          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Check Version
        run: echo $VERSION

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # specify your Node.js version
      
      - name: Install pnpm
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
        working-directory: ./litemall-vue

      - name: Install dependencies
        run: yarn build
        working-directory: ./litemall-vue

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image for amd64
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=amd64
          push: true
          tags: ${{ env.IMAGE_ORG }}/${{ env.IMAGE_NAME }}-amd64:latest

      - name: Build & Push Docker Image for arm64
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=arm64
          push: true
          tags: ${{ env.IMAGE_ORG }}/${{ env.IMAGE_NAME }}-arm64:latest
